### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by kjcolley7** [rhelmot/csaw16-finals-writeups#1]
Hey, great work on all of these challenges! I did want to point out however that our team, Knightsec, did solve the first part of Super Monster Ball during competition: https://nyfinals.csaw.io/team/522

**Comment by rhelmot** [comment]
Fixed. Did you solve it with a bot or by manually running around and catching them? I heard PPP had 102/103 with this method

**Comment by kjcolley7** [comment]
We had it botted. I wasn't the one from my team to solve it though so I don't know much detail.
